version: '3'

services:
  cs_nginx:
    image: nginx:1.15
    container_name: cs_nginx
    working_dir: /var/www
    depends_on: 
      - cs_db
    ports:
      - 8100:80
    links:
      - cs_php
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/logs:/var/log/nginx

  cs_php:
    # image: serhiicho/clothing_shop:php
    build: docker/php
    container_name: cs_php
    working_dir: /var/www
    ports:
      - 9001:9000
    volumes:
      - ./:/var/www
      - ./docker/php/php-fpm.conf:/etc/php-fpm.d/php-fpm.conf
      - ./docker/php/logs:/var/log/php
    depends_on:
      - cs_db

  cs_db:
    image: mysql:8.0
    container_name: cs_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 111111
      MYSQL_DATABASE: clothing_shop
    ports:
      - 3106:3306
    volumes:
      - ./docker/db/storage:/var/lib/mysql
      - ./docker/db/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./docker/db/logs:/var/log/mysql

  cs_composer:
    image: composer
    container_name: cs_composer
    volumes:
      - ./:/var/www
    working_dir: /var/www
    command: composer install

  cs_redis:
    image: redis:5.0
    container_name: cs_redis
    ports:
      - 6300:6379