version: '3'

services:
  nginx:
    image: nginx:1.15
    container_name: nginx
    working_dir: /var/www
    depends_on: 
      - db
    ports:
      - "80:80"
    links:
      - php
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/logs/nginx:/var/log/nginx

  php:
    build: ./docker/php
    container_name: php
    working_dir: /var/www
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www
      - ./docker/php/php-fpm.conf:/etc/php-fpm.d/php-fpm.conf
      - ./docker/logs/php:/var/log/php
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 111111
      MYSQL_DATABASE: clothing_shop
    volumes:
      - ./docker/db/storage:/var/lib/mysql
      - ./docker/db/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./docker/logs/db:/var/log/mysql

  composer:
    image: composer
    container_name: composer
    volumes:
      - ./:/var/www
    working_dir: /var/www
    command: composer install

  cache:
    image: redis:5.0
    container_name: cache
    ports:
      - 6379:6379